AboutMe/Models/Class.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace AboutMe.Models
{
    public class GradeCalcModel
    {
        [Required]
        [Range(0.00, 100.00)]
        public decimal assignmentScore { get; set; }

        [Required]
        [Range(0.00, 100.00)]
        public decimal groupProjectScore { get; set; }

        [Required]
        [Range(0.00, 100.00)]
        public decimal quizScore { get; set; }

        [Required]
        [Range(0.00, 100.00)]
        public decimal midtermScore { get; set; }

        [Required]
        [Range(0.00, 100.00)]
        public decimal finalScore { get; set; }

        [Required]
        [Range(0.00, 100.00)]
        public decimal intexScore { get; set; }
    }
}

AboutMe/Controllers/MainController.cs
using AboutMe.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AboutMe.Controllers
{
    public class MainController : Controller
    {
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult GradeCalc()
        {
            return View();
        }

        [HttpPost]
        public IActionResult GradeCalc(GradeCalcModel model)
        {
            return View();
        }
    }
}

AboutMe/Views/Main/GradeCalc.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Grade Calculator";
}

@model GradeCalcModel

<!--Grade Calculator form-->
<div class="col align-self-center d-flex justify-content-center">
    <form id="grade-calc" method="POST">
        <h4>Grade Calculator</h4>
        <div class="form-group">
            <label>Assignments Score</label>
            <input asp-for="assignmentScore" class="form-control" id="assignment" placeholder="Enter %">
        </div><br />
        <div class="form-group">
            <label>Group Projects Score</label>
            <input  asp-for="groupProjectScore" class="form-control" id="group-project" placeholder="Enter %">
        </div><br />
        <div class="form-group">
            <label>Quizzes Score</label>
            <input  asp-for="quizScore" class="form-control" id="quiz" placeholder="Enter %">
        </div><br />
        <div class="form-group">
            <label>Midterm Score</label>
            <input  asp-for="midtermScore" class="form-control" id="midterm" placeholder="Enter %">
        </div><br />
        <div class="form-group">
            <label>Final Score</label>
            <input  asp-for="finalScore" class="form-control" id="final" placeholder="Enter %">
        </div><br />
        <div class="form-group">
            <label>INTEX Score</label>
            <input  asp-for="intexScore" class="form-control" id="intex" placeholder="Enter %">
        </div>
        <br />
        <button id="btn" type="submit" class="btn btn-primary">Calculate</button>
        <br />
        <br />

        <!--Validation summary-->
        <div asp-validation-summary="All"></div>

        <!--Output results-->
        <h4 id="final-percent"></h4>
        <h4 id="final-letter"></h4>
    </form><br />

</div>

AboutMe/Views/Main/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "About Me";
}


<!--Picture of Scuba Diving-->
<img id="scuba-pic" src="img/scuba.jpg" class="img-fluid scuba-pic" />

<div class="container-fluid">
    <div class="row justify-content-evenly">
        <br />
        <br />
        <div id="about" class="col align-self-center">

            <!--Expectation for the class-->
            <p class="about-txt">I hope to hone my skills as a developer and learn enterprise level skills when building applications. I hope to become proficient in C# and ASP.NET.</p><br />
        </div>

        <div id="about2" class="col align-self-center">
            <!--Jobs interested in-->
            <div class="container">
                <p class="about-txt">Top 3 jobs i'm interested in upon graduation:</p>
                <ul>
                    <li class="about-txt">Developer</li>
                    <li class="about-txt">Cloud Solutions Architect</li>
                    <li class="about-txt">Some job in cybersecurity</li>
                </ul><br />
            </div>
        </div>
</div>

<br />
<br />

AboutMe/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>

    <head>
        <meta name="viewport" content="width=device-width" />
        <meta charset="utf-8" />
        <title>@ViewData["Title"]</title>
        <link rel="icon" href="https://img.icons8.com/color/96/null/cool--v1.png" />
        <link href="~/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet" /> <!--Bootstrap-->
        <link href="~/css/stylesheet.css" rel="stylesheet" /> <!--Custom CSS-->
    </head>

    <body>

        <!--Navbar-->
        <nav class="navbar navbar-dark bg-primary navbar-expand-lg">
            <a class="navbar-brand" asp-controller="Main" asp-action="Index">
                <img src="https://img.icons8.com/color/96/null/cool--v1.png" width="30" height="30" class="d-inline-block align-top" alt="">
                Justin Brown
            </a>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Main" asp-action="GradeCalc">Grade Calculator</a>
                    </li>
                </ul>
            </div>
        </nav>

        <!--Body-->
        <div>
            @RenderBody()
        </div>

        <!--Include Libraries-->
        <script src="~/lib/bootstrap/js/bootstrap.min.js"></script>
        <script src="~/lib/jquery/jquery-3.6.3.min.js"></script>

        <!--Grade calculator script-->
        <script src="~/js/gradeCalc.js"></script>

    </body>

</html>